### PR TITLE
Equivalent checks and notifications for full battery (and also ability to specify app name for notification)

### PR DESCRIPTION
**Pull request by mcolligan**
I use this every day and changed it slightly to fit my needs. I figured I'd pass these changes up in case they are of use to others.

There are two changes:

1. The ability to also check for when the battery is approaching a 'full' level when charging. Like the normal behaviour, it checks more frequently as it approaches that threshold.

2. The ability to provide a custom "app name" (terminology is from notify-send), instead of using PROGNAME, which it defaults to as before. Sometimes I like to include notify-send's app name argument in my notifications so I put this in.

I've added the appropriate changes to the man page. Let me know if there are any adjustments you think would make sense - I'm not too familiar with C so may have missed things!

### CODE REVIEW

**Comment by electrickite** [comment]
Thanks @mcolligan! Overall this looks good. I notice you added the variable battery check frequency even while the system is on AC power. I'm not sure I like this approach. Consider this scenario:

1. Computer is on battery power. Batsignal is monitoring battery level, critical level is 5 and full level is 95.
2. Battery discharges to 5 percent, the critical level, and batsignal starts checking levels every minute.
3. batsignal notifies the user that the battery is critical.
4. User plugs in computer
5. On next battery check, batsignal sees the system is on AC power, and sleeps for 90 minutes. (95-5)
6. Five minutes later, as the battery reaches 10 percent charge, the laptop is unplugged. The battery begins discharging.
7. Batsignal does not know about the state change, and will not check for another 85 minutes. This is more than enough time for the battery to completely discharge without notifying the user or running the danger level command.

To guard against this scenario, batsignal checks every 60 seconds (by default) while the system is on AC power. I would prefer to keep this behavior, even with the addition of the full battery message. Thoughts?

**Comment by mcolligan** [comment]
I had overlooked that scenario completely! Good spot.

So the behaviour we want when running on AC is:

If full == 0, check every 60 seconds (by default). However, I suppose the
duration could be increased as battery level is getting much higher than the
warning level.

If full != 0, check every 60 seconds when battery_level is below the warning
level. Duration can increase again as battery level increases, but then decrease
again as it approaches full.

i.e.:

    duration = multiplier;
    ...
    ...
    } else { /* charging */
      if (battery_level < warning) {
        battery_state = STATE_AC;
    
      } else if (full && battery_level >= full) {
        if (battery_state != STATE_FULL) {
          battery_state = STATE_FULL;
          notify(fullmsg);
        }
    
      } else if (full && battery_level > (warning + full)/2 ) {
        duration = (full - battery_level) * multiplier;
    
      } else {
        duration = (battery_level - warning) * multiplier;
      }
    }

How does that look?

**Comment by electrickite** [comment]
I’m not sure I see the reason to check less frequently when on AC power. The performance impact of a check every minute is negligible.

We really only care about reducing the frequency of processor wakes when on battery power, on AC I can’t see a reason not to check frequently. I’d rather keep the logic simple and not introduce new branches to that (already messy) conditional.

**Comment by mcolligan** [comment]
Understandable. We can reduce it down to just the state and notification:

    } else { /* charging */
        battery_state = STATE_AC;
        if (full && battery_level >= full && battery_state != STATE_FULL) {
            battery_state = STATE_FULL;
            notify(fullmsg);
	}
    }

If you'd like the PR I can commit this change, just let me know.

**Comment by electrickite** [comment]
Makes sense to me. If you want to update your branch, I'll accept the PR. Thanks again; glad you find it useful.

**Comment by mcolligan** [comment]
That's it committed there. Thanks for the nice little program.

**Comment by electrickite** [comment]
Thanks @mcolligan. Merged.

**Pull request merged**
