### PR TITLE
Use default notification expiration timeout and use an icon

### PR DESCRIPTION
**Pull request by noomly**

### CODE REVIEW

**Comment by electrickite** [comment]
Thanks for submitting the PR. I would prefer to keep the default notification behavior as-is, but I would consider merging a PR that made these settings configurable using command line arguments.

**Comment by noomly** [comment]
No problem! I have made the changes accessible via toggle-flags (-I for icon use and -e for setting notification expiration to default).

**Comment by electrickite** [comment]
Thanks! One more suggestion: `-I` should take a string argument to specify the icon to use. This PR also needs rebased against master to resolve conflicts.

**Comment by noomly** [comment]
Everything should be ok now.

**Comment by electrickite** [comment]
Looks good, thanks again!

**Pull request merged**
